/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tubes_sisforegistmk.View;

import java.awt.event.ActionListener;
import javax.swing.JButton;

/**
 *
 * @author desmoncode
 */
public class DashboardMahasiswa extends javax.swing.JFrame {

    /**
     * Creates new form DashboardMahasiswa
     */
    public DashboardMahasiswa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButtonKeluar = new javax.swing.JButton();
        jButtonTambah = new javax.swing.JButton();
        jButtonLihat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Mahasiswa");

        jLabel2.setText("Selamat Datang");

        jButtonKeluar.setText("Keluar");

        jButtonTambah.setText("Tambah Kelas");

        jButtonLihat.setText("Lihat Kelas");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(358, 358, 358)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 198, Short.MAX_VALUE)
                .addComponent(jButtonKeluar)
                .addGap(53, 53, 53))
            .addGroup(layout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addComponent(jButtonTambah)
                .addGap(70, 70, 70)
                .addComponent(jButtonLihat)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2))
                    .addComponent(jButtonKeluar))
                .addGap(137, 137, 137)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonTambah)
                    .addComponent(jButtonLihat))
                .addContainerGap(383, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JButton getjButtonKeluar() {
        return jButtonKeluar;
    }

    public void setjButtonKeluar(JButton jButtonKeluar) {
        this.jButtonKeluar = jButtonKeluar;
    }

    public JButton getjButtonLihat() {
        return jButtonLihat;
    }

    public void setjButtonLihat(JButton jButtonLihat) {
        this.jButtonLihat = jButtonLihat;
    }

    public JButton getjButtonTambah() {
        return jButtonTambah;
    }

    public void setjButtonTambah(JButton jButtonTambah) {
        this.jButtonTambah = jButtonTambah;
    }
    
    public void AddActionListener(ActionListener ae){
        jButtonKeluar.addActionListener(ae);
        jButtonLihat.addActionListener(ae);
        jButtonTambah.addActionListener(ae);
    }
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonKeluar;
    private javax.swing.JButton jButtonLihat;
    private javax.swing.JButton jButtonTambah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
