/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tubes_sisforegistmk.View;

import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author desmoncode
 */
public class DashboardAdmin extends javax.swing.JFrame {

    /**
     * Creates new form DashboardAdmin
     */
    public DashboardAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButtonDosen = new javax.swing.JButton();
        jButtonMahasiswa = new javax.swing.JButton();
        jButtonKelas = new javax.swing.JButton();
        jButtonMatakuliah = new javax.swing.JButton();
        jButtonKeluar = new javax.swing.JButton();
        jLabelWelcome = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setText("Administrator");

        jButtonDosen.setText("Kelola Dosen");

        jButtonMahasiswa.setText("Kelola Mahasiswa");

        jButtonKelas.setText("Kelola Kelas");

        jButtonMatakuliah.setText("Kelola Matakuliah");

        jButtonKeluar.setText("Keluar");
        jButtonKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonKeluarActionPerformed(evt);
            }
        });

        jLabelWelcome.setText("Selamat Datang");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelWelcome)
                .addGap(157, 157, 157)
                .addComponent(jButtonKeluar)
                .addGap(29, 29, 29))
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jButtonDosen, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addComponent(jButtonMahasiswa)
                .addGap(57, 57, 57)
                .addComponent(jButtonKelas, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(jButtonMatakuliah)
                .addGap(66, 66, 66))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelWelcome)
                        .addComponent(jButtonKeluar))
                    .addComponent(jLabel1))
                .addGap(226, 226, 226)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonDosen, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonMahasiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonKelas, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonMatakuliah, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(264, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonKeluarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonKeluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashboardAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashboardAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashboardAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashboardAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashboardAdmin().setVisible(true);
            }
        });
    }

    public JButton getjButtonDosen() {
        return jButtonDosen;
    }

    public void setjButtonDosen(JButton jButtonDosen) {
        this.jButtonDosen = jButtonDosen;
    }

    public JButton getjButtonKelas() {
        return jButtonKelas;
    }

    public void setjButtonKelas(JButton jButtonKelas) {
        this.jButtonKelas = jButtonKelas;
    }

    public JButton getjButtonKeluar() {
        return jButtonKeluar;
    }

    public void setjButtonKeluar(JButton jButtonKeluar) {
        this.jButtonKeluar = jButtonKeluar;
    }

    public JButton getjButtonMahasiswa() {
        return jButtonMahasiswa;
    }

    public void setjButtonMahasiswa(JButton jButtonMahasiswa) {
        this.jButtonMahasiswa = jButtonMahasiswa;
    }

    public JButton getjButtonMatakuliah() {
        return jButtonMatakuliah;
    }

    public void setjButtonMatakuliah(JButton jButtonMatakuliah) {
        this.jButtonMatakuliah = jButtonMatakuliah;
    }

    public JLabel getjLabelWelcome() {
        return jLabelWelcome;
    }

    public void setjLabelWelcome(JLabel jLabelWelcome) {
        this.jLabelWelcome = jLabelWelcome;
    }
    
    public void addActionListener(ActionListener al){
        jButtonDosen.addActionListener(al);
        jButtonKelas.addActionListener(al);
        jButtonMahasiswa.addActionListener(al);
        jButtonMatakuliah.addActionListener(al);
        jButtonKeluar.addActionListener(al);
         
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDosen;
    private javax.swing.JButton jButtonKelas;
    private javax.swing.JButton jButtonKeluar;
    private javax.swing.JButton jButtonMahasiswa;
    private javax.swing.JButton jButtonMatakuliah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelWelcome;
    // End of variables declaration//GEN-END:variables
}
